### ISSUE TITLE
Any plans to launch app on F-droid? 

### ISSUE THREAD

**Issue by L1VEWIR3** [certified84/AudioNote#1]

**Comment by certified84** [comment]
Hi there @L1VEWIR3 , I'm not quite familiar with F-droid.
Can you hit me up on Sammie_kt@pm.me so we can talk about it?

**Comment by shuvashish76** [comment]
Currently the app available on [izzy repo](https://apt.izzysoft.de/fdroid/index/apk/com.certified.audionote).

https://f-droid.org/en/about/
F-Droid is a non-profit alternative app store for FOSS apps, where applications in the repository are built from source.

Ping @IzzySoft _(he is one of the maintainer there)_ for help.

**Comment by IzzySoft** [comment]
Well, I know it's in my repo – I've put it there :rofl: So what was I pinged for, how can I help?

**Comment by shuvashish76** [comment]
> I'm not quite familiar with F-droid.

@IzzySoft For general overview about F-Droid & how it works. Pinged you for the links as your reply looks professional 😅

@certified84 check this comment : https://github.com/freeCodeCamp/mobile/issues/199#issuecomment-1038170882

**Comment by IzzySoft** [comment]
@shuvashish76 you have my explicit permission to post those links :smile:

* [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1) (the start of the article series)
* the [`fdroid`](https://android.izzysoft.de/articles/tagged/fdroid) tag for more on the topic

**Comment by certified84** [comment]
Hey guys, I've gone through the comments and I find @IzzySoft F-Droid repo quite interesting. Thanks for sharing @L1VEWIR3 and @shuvashish76. Launching the app on F-droid sounds fun🤗🤗🤗

**Comment by shuvashish76** [comment]
A RFP has been opened here : https://gitlab.com/fdroid/rfp/-/issues/2021

F-Droid requirements

- [ ] The upstream app source code repo contains the app metadata _(summary/description/images/changelog/etc)_ in a [Fastlane](https://gitlab.com/snippets/1895688) or [Triple-T](https://gitlab.com/snippets/1901490) folder structure.

**Comment by IzzySoft** [comment]
^^ just push the button :smiley:

**Comment by IzzySoft** [comment]
@certified84 guess I'd need your help with the F-Droid build. It builds fine so far, but not "reproducible" (with reproducible builds, F-Droid would ship the APK you build and sign). You can [find my notes here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12961#note_1366104266) (and are welcome to chime in). The current question is, let me quote from a team mate:

> The order of those files is different. Maybe upstream built the apk with android studio. Please ask them building it from command line.

Can that be done? Either from the commit the current tag points to – or from a later one where Fastlane is available, too (in that case please let me know which commit you took, so I update that on F-Droid's end for the reproducible-check). Thanks in advance!

**Comment by certified84** [comment]
Hi @IzzySoft check the latest release [here](https://github.com/certified84/AudioNote/releases/tag/v0.1.5)

Fastlane is covered by the tag

**Comment by IzzySoft** [comment]
Version bumped, CI running now, thanks!

**Comment by IzzySoft** [comment]
Well, [this](https://github.com/certified84/AudioNote/blob/v0.1.5/app/build.gradle#L113) was a very bad idea: Firebase is a show-stopper for F-Droid. Can you remove that again, or at least provide a build flavor without? Else we have to abandon the inclusion.

**Comment by certified84** [comment]
Ok, no worries. I’ll do that and ping you again

**Comment by certified84** [comment]
@IzzySoft, fixed it [here](https://github.com/certified84/AudioNote/releases/tag/v0.1.5.1)

**Comment by IzzySoft** [comment]
Thanks! YAML updated and pushed. Waiting for the CI then.

**Comment by IzzySoft** [comment]
```diff
diff -r /tmp/tmp.95HiDjck9v/a/kotlin-tooling-metadata.json /tmp/tmp.95HiDjck9v/b/kotlin-tooling-metadata.json
4c4
<   "buildSystemVersion": "8.0.2",
---
>   "buildSystemVersion": "8.0",
```

That file seems to be produced at build time. Is that needed? It's the only thing keeping the build from being reproducible now.

**Comment by certified84** [comment]
I’ll take a look at it

**Comment by certified84** [comment]
@IzzySoft can you try it again?
