### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [certified84/AudioNote#11]
Please add the Android 13 "Themed App Icons" feature.

![Screenshot_2023-05-01-22-48-16-314_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/235514475-2345fa7f-a793-42d2-8f9c-7e01433b29da.jpg)

Thanks 🙏

**Comment by certified84** [comment]
#12 will fix this

**Comment by xmha97** [comment]
Thanks 🙏
