### ISSUE TITLE
Discarded notes are not deleted

### ISSUE THREAD

**Issue by gdonisi** [certified84/AudioNote#6]
The size of these files is minuscule, so this isn't something urgent to work on. But as you can see, every time I stop recording and refresh, there's a new file in the folder. The same happens if I click the Back button instead of saving.

https://user-images.githubusercontent.com/82442402/155750106-9a2127f9-a25c-49bb-b730-65c9ce952d27.mp4

**Comment by certified84** [comment]
Hi @gdonisi,

I’ll look into this and notify you when there’s a fix
